parameters:
    database.host:     127.0.0.1
    database.port:     3306
    database.name:     test
    database.user:     '%cs.database.user%'
    database.password: '%cs.database.password%'
    # You should uncomment this if you want use pdo_sqlite
    # database.path: "%kernel.root_dir%/data.db3"

    mailer.transport:  smtp
    mailer.host:       smtp.sendgrid.net
    mailer.port:	   587
    mailer.user:       ~
    mailer.password:   ~
    mail.encryption:   ~

    # A secret key that's used to generate certain security-related tokens
    secret:            ThisTokenIsNotSoSecretChangeIt
    
    # Instagram API keys
    instagram.client.id: randomstrings
    instagram.client.secret: randomstrings
   