# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    my_user_provider.class: AppBundle\Security\Core\User\FOSUBUserProvider
    user_service.class: AppBundle\Core\Service\UserService
    user_dao.class: AppBundle\Core\Dao\UserDAO
    social_profile_util.class: AppBundle\Util\SocialProfileUtil
    social_service.class: AppBundle\Core\Service\SocialService
    social_statistic_dao.class: AppBundle\Core\Dao\SocialStatisticDAO
    campaign_service.class: AppBundle\Core\Service\CampaignService
    campaign_dao.class: AppBundle\Core\Dao\CampaignDAO

services:
  
    user_dao:
        class: "%user_dao.class%"
        arguments: ["@doctrine.orm.entity_manager","@logger"]
    
    user_service:
        class: "%user_service.class%"
        arguments: ["@user_dao","@logger"]
        
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: ["@fos_user.user_manager",{instagram: instagramId},"%instagram.client.id%","%instagram.client.secret%","@logger", "@user_service"]
        tags:
            - { name: monolog.logger }

    social_statistic_dao:
            class: "%social_statistic_dao.class%"
            arguments: ["@doctrine.orm.entity_manager","@logger"]

    social_service:
        class: "%social_service.class%"
        arguments: ["@social_statistic_dao","@logger"]
            
    social_profile_util:
        class: "%social_profile_util.class%"
        arguments: ["@user_service","@logger", "@social_service","@sonata.notification.backend"]

    campaign_dao:
            class: "%campaign_dao.class%"
            arguments: ["@doctrine.orm.entity_manager","@logger"]

    campaign_service:
        class: "%campaign_service.class%"
        arguments: ["@campaign_dao","@logger"]


